# Generated by Django 2.2 on 2019-01-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='uzytkownik',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='data_ostatniej_modyfikacji',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Statuses'),
        ),
    ]
