# Generated by Django 2.2 on 2019-01-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketlist', '0003_auto_20190112_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
