# Generated by Django 2.2 on 2019-01-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketlist', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='firma',
            field=models.CharField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
