# Generated by Django 2.2 on 2019-01-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketlist', '0005_auto_20190112_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damagename', models.CharField(max_length=254)),
                ('repairprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Devicedamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damagedescription', models.TextField()),
                ('damagedpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Damage')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Devicemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_ostatniej_modyfikacji', models.DateTimeField(auto_now=True)),
                ('uzytkownik', models.CharField(default=0, max_length=254)),
                ('firma', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='aplikacja',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='typ',
        ),
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
        migrations.DeleteModel(
            name='Apps',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Status'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Devicemodel'),
        ),
        migrations.AddField(
            model_name='device',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Ticket'),
        ),
    ]
