# Generated by Django 2.2 on 2019-01-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketlist', '0006_auto_20190124_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedamage',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketlist.Ticket'),
        ),
    ]
