# Generated by Django 2.2 on 2019-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketlist', '0007_devicedamage_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='damagetype',
            field=models.CharField(default='wizualne', max_length=254),
        ),
    ]
